# Function Info -----------------------------------------------------------
# Name:      EIAsim.R (EIA price path simulation)
# Author(s): Jon Wilkey
# Contact:   jon.wilkey@gmail.com


# Inputs ------------------------------------------------------------------

# nrun - Number of Monte-Carlo simulation runs

# FPPdate - Date associated with oil/gas FPPs (e.g. "2004-12-01")

# Eoil/Egas - EIA AEO error CDF matrix for oil and gas forecasts, respectively

# op.FC - EIA reference forecast for oil prices, adjusted for inflation to basis
# $/bbl and on a monthly basis

# gp.FC - Same as op.FC but for gas prices and in units of basis $/MCF


# Outputs -----------------------------------------------------------------

# opsim/gpsim - a matrix of oil/gas prices in basis $/bbl or $/MCF with rows =
# random draws (1 row for each MC run) and columns = time steps


# Description -------------------------------------------------------------

# This function returns a set of price paths that are randomly generated by 
# adjusting EIA's reference oil and gas price forecasts by the historically
# observed errors in their forecasts.

# The input forecasts op.FC and gp.FC are adjusted by multiplying the forecast
# by a randomly selected row from the EIA error CDF matrices Eoil or Egas. This
# effectively adjusts the forecast up or down by a percentage that is
# representative of the range of error that exists in EIA's forecasts.


# Function ----------------------------------------------------------------

EIAsim <- function(nrun, Eoil, Egas, op.FC, gp.FC) {
  
  # Energy price path simulation --------------------------------------------
  
  # Pick random rows for Eoil and Egas and then multiply op and gp by the
  # corresponding error % to get resulting price paths
  
  # Make random row picks
  temp <- round(runif(nrun, min = 1, max = nrow(Eoil)))
  
  # Preallocate space for results
  opsim <- matrix(0, nrow = nrun, ncol = length(op.FC))
  gpsim <- opsim
  
  # For each time step
  for (i in 1:length(op.FC)) {
    opsim[,i] <- op.FC[i]*(1-Eoil[temp,i]/100)
    gpsim[,i] <- gp.FC[i]*(1-Egas[temp,i]/100)
  }
  
  
  # Return results ----------------------------------------------------------
  
  return(list(opsim, gpsim))
}