# Function Info -----------------------------------------------------------
# Name:      EIAsim.R (EIA price path simulation)
# Author(s): Jon Wilkey
# Contact:   jon.wilkey@gmail.com


# Inputs ------------------------------------------------------------------

# nrun - Number of Monte-Carlo simulation runs

# FPPdate - Date associated with oil/gas FPPs (e.g. "2004-12-01")

# Eoil/Egas - EIA AEO error CDF matrix for oil and gas forecasts, respectively

# EoilFrac/EgasFrac - EIA AEO error CDF matrix for oil and gas forecasts with
# fractional relative error, respectively

# op.FC - EIA reference forecast for oil prices, adjusted for inflation to basis
# $/bbl and on a monthly basis

# gp.FC - Same as op.FC but for gas prices and in units of basis $/MCF

# type - lcharacter string specifying relative error quantification method. Valid
# options are "RE Direct" for relative error with directionality (for RE = (FP -
# AP) / FP data where RE = relative error, FP = forecasted price, and AP = 
# actual price) or "RE Frac" for relative fractional error (for RE = FP / AP IFF
# AP > FP | RE = AP / FP IFF FP > AP data).

# fracProb - probability between 0 and 1 that forecasted price will be
# over-predicting (SP = FC / RE) vs. under-predicting (SP = FC * RE)


# Outputs -----------------------------------------------------------------

# opsim/gpsim - a matrix of oil/gas prices in basis $/bbl or $/MCF with rows =
# random draws (1 row for each MC run) and columns = time steps


# Description -------------------------------------------------------------

# This function returns a set of price paths that are randomly generated by 
# adjusting EIA's reference oil and gas price forecasts by the historically
# observed errors in their forecasts.

# The input forecasts op.FC and gp.FC are adjusted by multiplying the forecast
# by a randomly selected row from the EIA error CDF matrices Eoil or Egas. This
# effectively adjusts the forecast up or down by a percentage that is
# representative of the range of error that exists in EIA's forecasts.

# If desired, the historical skew in EIA's AEO forecast can be removed by 
# multiplying the randomly selected relative error percentage by +/- 1. Random 
# values are selected from a binomial distribution with a 50% probability cutoff
# (50% will be -1, 50% will be +1). This has the net effect of mirroring the PDF
# for the relative error about a mean of 0.


# Function ----------------------------------------------------------------

EIAsim <- function(nrun, Eoil, Egas, EoilFrac, EgasFrac, op.FC, gp.FC, type,
                   fracProb) {
  
  # Energy price path simulation --------------------------------------------
  
  # Pick random rows for Eoil and Egas and then multiply op and gp by the
  # corresponding error % to get resulting price paths
  
  # Make random row picks
  temp <- round(runif(nrun, min = 1, max = nrow(Eoil)))
  
  # Preallocate space for results
  opsim <- matrix(0, nrow = nrun, ncol = length(op.FC))
  gpsim <- opsim
  
  switch(type,
         
         "direct" = {
           
           # For each time step
           for (i in 1:length(op.FC)) {
             
             opsim[,i] <- op.FC[i]*(1-Eoil[temp,i]/100)
             gpsim[,i] <- gp.FC[i]*(1-Egas[temp,i]/100)
             }
           },
           
           "frac" = {
             
             # Pick direction of forecast error (under/over predicting)
             direct.oil <- rbinom(n = nrun, size = 1, prob = fracProb)
             direct.gas <- rbinom(n = nrun, size = 1, prob = fracProb)
             
             # For each MC simulation
             for (j in 1:nrun) {
               
               # For oil - if the forecasting is under-predicting
               if(direct.oil[j] == 0){
                 
                 opsim[j, ] <- op.FC * EoilFrac[temp[j], ]
                 
               } else {
                 
                 opsim[j, ] <- op.FC / EoilFrac[temp[j], ]
               }
               
               # For gas - if the forecasting is under-predicting
               if(direct.gas[j] == 0){
                 
                 gpsim[j, ] <- gp.FC * EgasFrac[temp[j], ]
                 
               } else {
                 
                 gpsim[j, ] <- gp.FC / EgasFrac[temp[j], ]
               }
             }
           }
  )
  
  
  # Return results ----------------------------------------------------------
  
  return(list(op = opsim, gp = gpsim))
}